// CarAdvisers App

export const carAdvisersImages = {
  splash: {
    header: new URL("./ca/caHeader2.png", import.meta.url).href,
  },
  home: {
    screen1: new URL("./ca/home/1.png", import.meta.url).href,
    screen2: new URL("./ca/home/2.png", import.meta.url).href,
    screen3: new URL("./ca/home/3.png", import.meta.url).href,
    screen4: new URL("./ca/home/4.png", import.meta.url).href,
    screen5: new URL("./ca/home/5.png", import.meta.url).href,
    screen6: new URL("./ca/home/6.png", import.meta.url).href,
    screen7: new URL("./ca/home/7.png", import.meta.url).href,
    screen8: new URL("./ca/home/8.png", import.meta.url).href,
    screen9: new URL("./ca/home/9.png", import.meta.url).href,
    screen10: new URL("./ca/home/10.png", import.meta.url).href,
    screen11: new URL("./ca/home/11.png", import.meta.url).href,
    screen12: new URL("./ca/home/12.png", import.meta.url).href,
    screen13: new URL("./ca/home/13.png", import.meta.url).href,
    screen14: new URL("./ca/home/14.png", import.meta.url).href,
    screen15: new URL("./ca/home/15.png", import.meta.url).href,
    screen16: new URL("./ca/home/16.png", import.meta.url).href,
    screen17: new URL("./ca/home/17.png", import.meta.url).href,
    screen18: new URL("./ca/home/18.png", import.meta.url).href,
    screen19: new URL("./ca/home/19.png", import.meta.url).href,
    screen20: new URL("./ca/home/20.png", import.meta.url).href,
    screen21: new URL("./ca/home/21.png", import.meta.url).href,
    screen22: new URL("./ca/home/22.png", import.meta.url).href,
    screen23: new URL("./ca/home/23.png", import.meta.url).href,
    screen24: new URL("./ca/home/24.png", import.meta.url).href,
    screen25: new URL("./ca/home/25.png", import.meta.url).href,
    screen26: new URL("./ca/home/26.png", import.meta.url).href,
    screen27: new URL("./ca/home/27.png", import.meta.url).href,
    screen28: new URL("./ca/home/28.png", import.meta.url).href,
    screen29: new URL("./ca/home/29.png", import.meta.url).href,
    screen30: new URL("./ca/home/30.png", import.meta.url).href,
    screen31: new URL("./ca/home/31.png", import.meta.url).href,
    screen32: new URL("./ca/home/32.png", import.meta.url).href,
    screen33: new URL("./ca/home/33.png", import.meta.url).href,
    screen34: new URL("./ca/home/34.png", import.meta.url).href,
    screen35: new URL("./ca/home/35.png", import.meta.url).href,
    screen36: new URL("./ca/home/36.png", import.meta.url).href,
  },
  auth: {
    screen1: new URL("./ca/auth/1.png", import.meta.url).href,
    screen2: new URL("./ca/auth/2.png", import.meta.url).href,
    screen3: new URL("./ca/auth/3.png", import.meta.url).href,
    screen4: new URL("./ca/auth/4.png", import.meta.url).href,
    screen5: new URL("./ca/auth/5.png", import.meta.url).href,
    screen6: new URL("./ca/auth/6.png", import.meta.url).href,
    screen7: new URL("./ca/auth/7.png", import.meta.url).href,
    screen8: new URL("./ca/auth/8.png", import.meta.url).href,
    screen9: new URL("./ca/auth/9.png", import.meta.url).href,
    screen10: new URL("./ca/auth/10.png", import.meta.url).href,
    screen11: new URL("./ca/auth/11.png", import.meta.url).href,
    screen12: new URL("./ca/auth/12.png", import.meta.url).href,
    screen13: new URL("./ca/auth/13.png", import.meta.url).href,
    screen14: new URL("./ca/auth/14.png", import.meta.url).href,
    screen15: new URL("./ca/auth/15.png", import.meta.url).href,
    screen16: new URL("./ca/auth/16.png", import.meta.url).href,
  },
  details: {
    screen1: new URL("./ca/details/1.png", import.meta.url).href,
    screen2: new URL("./ca/details/2.png", import.meta.url).href,
    screen3: new URL("./ca/details/3.png", import.meta.url).href,
    screen4: new URL("./ca/details/4.png", import.meta.url).href,
    screen5: new URL("./ca/details/5.png", import.meta.url).href,
    screen6: new URL("./ca/details/6.png", import.meta.url).href,
    screen7: new URL("./ca/details/7.png", import.meta.url).href,
    screen8: new URL("./ca/details/8.png", import.meta.url).href,
    screen9: new URL("./ca/details/9.png", import.meta.url).href,
    screen10: new URL("./ca/details/10.png", import.meta.url).href,
    screen11: new URL("./ca/details/11.png", import.meta.url).href,
    screen12: new URL("./ca/details/12.png", import.meta.url).href,
    screen13: new URL("./ca/details/13.png", import.meta.url).href,
    screen14: new URL("./ca/details/14.png", import.meta.url).href,
    screen15: new URL("./ca/details/15.png", import.meta.url).href,
    screen16: new URL("./ca/details/16.png", import.meta.url).href,
    screen17: new URL("./ca/details/17.png", import.meta.url).href,
    screen18: new URL("./ca/details/18.png", import.meta.url).href,
    screen19: new URL("./ca/details/19.png", import.meta.url).href,
    screen20: new URL("./ca/details/20.png", import.meta.url).href,
    screen21: new URL("./ca/details/21.png", import.meta.url).href,
    screen22: new URL("./ca/details/22.png", import.meta.url).href,
    screen23: new URL("./ca/details/23.png", import.meta.url).href,
    screen24: new URL("./ca/details/24.png", import.meta.url).href,
    screen25: new URL("./ca/details/25.png", import.meta.url).href,
    screen26: new URL("./ca/details/26.png", import.meta.url).href,
    screen27: new URL("./ca/details/27.png", import.meta.url).href,
    screen28: new URL("./ca/details/28.png", import.meta.url).href,
    screen29: new URL("./ca/details/29.png", import.meta.url).href,
    screen30: new URL("./ca/details/30.png", import.meta.url).href,
    screen31: new URL("./ca/details/31.png", import.meta.url).href,
    screen32: new URL("./ca/details/32.png", import.meta.url).href,
    screen33: new URL("./ca/details/33.png", import.meta.url).href,
    screen34: new URL("./ca/details/34.png", import.meta.url).href,
    screen35: new URL("./ca/details/35.png", import.meta.url).href,
    screen36: new URL("./ca/details/36.png", import.meta.url).href,
    screen37: new URL("./ca/details/37.png", import.meta.url).href,
    screen38: new URL("./ca/details/38.png", import.meta.url).href,
    screen39: new URL("./ca/details/39.png", import.meta.url).href,
    screen40: new URL("./ca/details/40.png", import.meta.url).href,
  },
  messages: {
    screen1: new URL("./ca/messages/1.png", import.meta.url).href,
    screen2: new URL("./ca/messages/2.png", import.meta.url).href,
    screen3: new URL("./ca/messages/3.png", import.meta.url).href,
  },
  myAds: {
    screen1: new URL("./ca/my-ads/1.png", import.meta.url).href,
    screen2: new URL("./ca/my-ads/2.png", import.meta.url).href,
    screen3: new URL("./ca/my-ads/3.png", import.meta.url).href,
    screen4: new URL("./ca/my-ads/4.png", import.meta.url).href,
    screen5: new URL("./ca/my-ads/5.png", import.meta.url).href,
    screen6: new URL("./ca/my-ads/6.png", import.meta.url).href,
    screen7: new URL("./ca/my-ads/7.png", import.meta.url).href,
    screen8: new URL("./ca/my-ads/8.png", import.meta.url).href,
    screen9: new URL("./ca/my-ads/9.png", import.meta.url).href,
    screen10: new URL("./ca/my-ads/10.png", import.meta.url).href,
    screen11: new URL("./ca/my-ads/11.png", import.meta.url).href,
    screen12: new URL("./ca/my-ads/12.png", import.meta.url).href,
    screen13: new URL("./ca/my-ads/13.png", import.meta.url).href,
    screen14: new URL("./ca/my-ads/14.png", import.meta.url).href,
    screen15: new URL("./ca/my-ads/15.png", import.meta.url).href,
  },
  postAds: {
    screen1: new URL("./ca/post-ad/1.png", import.meta.url).href,
    screen2: new URL("./ca/post-ad/2.png", import.meta.url).href,
    screen3: new URL("./ca/post-ad/3.png", import.meta.url).href,
    screen4: new URL("./ca/post-ad/4.png", import.meta.url).href,
    screen5: new URL("./ca/post-ad/5.png", import.meta.url).href,
    screen6: new URL("./ca/post-ad/6.png", import.meta.url).href,
    screen7: new URL("./ca/post-ad/7.png", import.meta.url).href,
    screen8: new URL("./ca/post-ad/8.png", import.meta.url).href,
    screen9: new URL("./ca/post-ad/9.png", import.meta.url).href,
  },
  products: {
    screen1: new URL("./ca/products/1.png", import.meta.url).href,
    screen2: new URL("./ca/products/2.png", import.meta.url).href,
    screen3: new URL("./ca/products/3.png", import.meta.url).href,
    screen4: new URL("./ca/products/4.png", import.meta.url).href,
    screen5: new URL("./ca/products/5.png", import.meta.url).href,
    screen6: new URL("./ca/products/6.png", import.meta.url).href,
    screen7: new URL("./ca/products/7.png", import.meta.url).href,
    screen8: new URL("./ca/products/8.png", import.meta.url).href,
    screen9: new URL("./ca/products/9.png", import.meta.url).href,
    screen10: new URL("./ca/products/10.png", import.meta.url).href,
    screen11: new URL("./ca/products/11.png", import.meta.url).href,
    screen12: new URL("./ca/products/12.png", import.meta.url).href,
    screen13: new URL("./ca/products/13.png", import.meta.url).href,
    screen14: new URL("./ca/products/14.png", import.meta.url).href,
    screen15: new URL("./ca/products/15.png", import.meta.url).href,
    screen16: new URL("./ca/products/16.png", import.meta.url).href,
    screen17: new URL("./ca/products/17.png", import.meta.url).href,
    screen18: new URL("./ca/products/18.png", import.meta.url).href,
    screen19: new URL("./ca/products/19.png", import.meta.url).href,
  },
  search: {
    screen1: new URL("./ca/search/1.png", import.meta.url).href,
    screen2: new URL("./ca/search/2.png", import.meta.url).href,
    screen3: new URL("./ca/search/3.png", import.meta.url).href,
    screen4: new URL("./ca/search/4.png", import.meta.url).href,
    screen5: new URL("./ca/search/5.png", import.meta.url).href,
    screen6: new URL("./ca/search/6.png", import.meta.url).href,
    screen7: new URL("./ca/search/7.png", import.meta.url).href,
    screen8: new URL("./ca/search/8.png", import.meta.url).href,
    screen9: new URL("./ca/search/9.png", import.meta.url).href,
    screen10: new URL("./ca/search/10.png", import.meta.url).href,
    screen11: new URL("./ca/search/11.png", import.meta.url).href,
    screen12: new URL("./ca/search/12.png", import.meta.url).href,
  },
  account: {
    screen1: new URL("./ca/account/1.png", import.meta.url).href,
    screen2: new URL("./ca/account/2.png", import.meta.url).href,
    screen3: new URL("./ca/account/3.png", import.meta.url).href,
    screen4: new URL("./ca/account/4.png", import.meta.url).href,
    screen5: new URL("./ca/account/5.png", import.meta.url).href,
    screen6: new URL("./ca/account/6.png", import.meta.url).href,
    screen7: new URL("./ca/account/7.png", import.meta.url).href,
    screen8: new URL("./ca/account/8.png", import.meta.url).href,
    screen9: new URL("./ca/account/9.png", import.meta.url).href,
    screen10: new URL("./ca/account/10.png", import.meta.url).href,
    screen11: new URL("./ca/account/11.png", import.meta.url).href,
    screen12: new URL("./ca/account/12.png", import.meta.url).href,
    screen13: new URL("./ca/account/13.png", import.meta.url).href,
    screen14: new URL("./ca/account/14.png", import.meta.url).href,
    screen15: new URL("./ca/account/15.png", import.meta.url).href,
    screen16: new URL("./ca/account/16.png", import.meta.url).href,
    screen17: new URL("./ca/account/17.png", import.meta.url).href,
    screen18: new URL("./ca/account/18.png", import.meta.url).href,
    screen19: new URL("./ca/account/19.png", import.meta.url).href,
    screen20: new URL("./ca/account/20.png", import.meta.url).href,
    screen21: new URL("./ca/account/21.png", import.meta.url).href,
    screen22: new URL("./ca/account/22.png", import.meta.url).href,
    screen23: new URL("./ca/account/23.png", import.meta.url).href,
    screen24: new URL("./ca/account/24.png", import.meta.url).href,
    screen25: new URL("./ca/account/25.png", import.meta.url).href,
    screen26: new URL("./ca/account/26.png", import.meta.url).href,
    screen27: new URL("./ca/account/27.png", import.meta.url).href,
    screen28: new URL("./ca/account/28.png", import.meta.url).href,
    screen29: new URL("./ca/account/29.png", import.meta.url).href,
    screen30: new URL("./ca/account/30.png", import.meta.url).href,
    screen31: new URL("./ca/account/31.png", import.meta.url).href,
    screen32: new URL("./ca/account/32.png", import.meta.url).href,
    screen33: new URL("./ca/account/33.png", import.meta.url).href,
    screen34: new URL("./ca/account/34.png", import.meta.url).href,
    screen35: new URL("./ca/account/35.png", import.meta.url).href,
    screen36: new URL("./ca/account/36.png", import.meta.url).href,
    screen37: new URL("./ca/account/37.png", import.meta.url).href,
  },
};

// Morsety User App
export const morsetyImages = {
  splash: {
    header: new URL("./morsety/splash/header.png", import.meta.url).href,
  },
  onboarding: {
    screen1: new URL("./morsety/onboarding/1.png", import.meta.url).href,
    screen2: new URL("./morsety/onboarding/2.png", import.meta.url).href,
    screen3: new URL("./morsety/onboarding/3.png", import.meta.url).href,
  },
  auth: {
    screen1: new URL("./morsety/auth/1.png", import.meta.url).href,
    screen2: new URL("./morsety/auth/2.png", import.meta.url).href,
    screen3: new URL("./morsety/auth/3.png", import.meta.url).href,
    screen4: new URL("./morsety/auth/4.png", import.meta.url).href,
    screen5: new URL("./morsety/auth/5.png", import.meta.url).href,
    screen6: new URL("./morsety/auth/6.png", import.meta.url).href,
    screen7: new URL("./morsety/auth/7.png", import.meta.url).href,
  },
  home: {
    screen1: new URL("./morsety/home/h1.png", import.meta.url).href,
    screen2: new URL("./morsety/home/h2.png", import.meta.url).href,
    screen3: new URL("./morsety/home/h3.png", import.meta.url).href,
    screen4: new URL("./morsety/home/h4.png", import.meta.url).href,
    screen6: new URL("./morsety/home/h6.png", import.meta.url).href,
    screen7: new URL("./morsety/home/h7.png", import.meta.url).href,
  },
  details: {
    screen1: new URL("./morsety/details/1.PNG", import.meta.url).href,
    screen2: new URL("./morsety/details/2.PNG", import.meta.url).href,
    screen3: new URL("./morsety/details/3.PNG", import.meta.url).href,
    screen4: new URL("./morsety/details/4.PNG", import.meta.url).href,
    screen5: new URL("./morsety/details/5.PNG", import.meta.url).href,
    screen6: new URL("./morsety/details/6.PNG", import.meta.url).href,
    screen7: new URL("./morsety/details/7.PNG", import.meta.url).href,
    screen8: new URL("./morsety/details/8.PNG", import.meta.url).href,
  },
  booking: {
    screen1: new URL("./morsety/bookings/1.PNG", import.meta.url).href,
    screen2: new URL("./morsety/bookings/2.PNG", import.meta.url).href,
    screen3: new URL("./morsety/bookings/3.PNG", import.meta.url).href,
    screen4: new URL("./morsety/bookings/4.PNG", import.meta.url).href,
    screen5: new URL("./morsety/bookings/5.PNG", import.meta.url).href,
    screen6: new URL("./morsety/bookings/6.PNG", import.meta.url).href,
    screen7: new URL("./morsety/bookings/7.PNG", import.meta.url).href,
    screen8: new URL("./morsety/bookings/8.PNG", import.meta.url).href,
    screen9: new URL("./morsety/bookings/9.PNG", import.meta.url).href,
  },
  search: {
    screen1: new URL("./morsety/search/1.PNG", import.meta.url).href,
    screen2: new URL("./morsety/search/2.PNG", import.meta.url).href,
    screen3: new URL("./morsety/search/3.PNG", import.meta.url).href,
    screen4: new URL("./morsety/search/4.PNG", import.meta.url).href,
    screen5: new URL("./morsety/search/5.PNG", import.meta.url).href,
    screen6: new URL("./morsety/search/6.PNG", import.meta.url).href,
    screen7: new URL("./morsety/search/7.PNG", import.meta.url).href,
  },
  messages: {
    screen1: new URL("./morsety/messages/1.PNG", import.meta.url).href,
    screen2: new URL("./morsety/messages/2.PNG", import.meta.url).href,
    screen3: new URL("./morsety/messages/3.PNG", import.meta.url).href,
    screen4: new URL("./morsety/messages/4.PNG", import.meta.url).href,
    screen5: new URL("./morsety/messages/5.PNG", import.meta.url).href,
  },
  account: {
    screen1: new URL("./morsety/account/1.PNG", import.meta.url).href,
    screen2: new URL("./morsety/account/2.PNG", import.meta.url).href,
    screen3: new URL("./morsety/account/3.PNG", import.meta.url).href,
    screen4: new URL("./morsety/account/4.PNG", import.meta.url).href,
    screen5: new URL("./morsety/account/5.PNG", import.meta.url).href,
    screen6: new URL("./morsety/account/6.PNG", import.meta.url).href,
  },
};

// Morsety Business App
export const morsetyBusinessImages = {
  splash: {
    header: new URL("./morsety-business/splash/header.png", import.meta.url)
      .href,
  },
  home: {
    screen1: new URL("./morsety-business/home/1.png", import.meta.url).href,
    screen2: new URL("./morsety-business/home/2.png", import.meta.url).href,
    screen3: new URL("./morsety-business/home/3.png", import.meta.url).href,
    screen4: new URL("./morsety-business/home/4.png", import.meta.url).href,
  },
  auth: {
    screen1: new URL("./morsety-business/auth/1.png", import.meta.url).href,
    screen2: new URL("./morsety-business/auth/2.png", import.meta.url).href,
    screen3: new URL("./morsety-business/auth/3.png", import.meta.url).href,
    screen4: new URL("./morsety-business/auth/4.png", import.meta.url).href,
    screen5: new URL("./morsety-business/auth/5.png", import.meta.url).href,
    screen6: new URL("./morsety-business/auth/6.png", import.meta.url).href,
    screen7: new URL("./morsety-business/auth/7.png", import.meta.url).href,
    screen8: new URL("./morsety-business/auth/8.png", import.meta.url).href,
    screen9: new URL("./morsety-business/auth/9.png", import.meta.url).href,
    screen10: new URL("./morsety-business/auth/10.png", import.meta.url).href,
    screen11: new URL("./morsety-business/auth/11.png", import.meta.url).href,
    screen12: new URL("./morsety-business/auth/12.png", import.meta.url).href,
    screen13: new URL("./morsety-business/auth/13.png", import.meta.url).href,
  },
  branches: {
    screen1: new URL("./morsety-business/branches/1.png", import.meta.url).href,
    screen2: new URL("./morsety-business/branches/2.png", import.meta.url).href,
    screen3: new URL("./morsety-business/branches/3.png", import.meta.url).href,
    screen4: new URL("./morsety-business/branches/4.png", import.meta.url).href,
    screen5: new URL("./morsety-business/branches/5.png", import.meta.url).href,
    screen6: new URL("./morsety-business/branches/6.png", import.meta.url).href,
    screen7: new URL("./morsety-business/branches/7.png", import.meta.url).href,
    screen8: new URL("./morsety-business/branches/8.png", import.meta.url).href,
    screen9: new URL("./morsety-business/branches/9.png", import.meta.url).href,
    screen10: new URL("./morsety-business/branches/10.png", import.meta.url)
      .href,
    screen11: new URL("./morsety-business/branches/11.png", import.meta.url)
      .href,
    screen12: new URL("./morsety-business/branches/12.png", import.meta.url)
      .href,
    screen13: new URL("./morsety-business/branches/13.png", import.meta.url)
      .href,
    screen14: new URL("./morsety-business/branches/14.png", import.meta.url)
      .href,
    screen15: new URL("./morsety-business/branches/15.png", import.meta.url)
      .href,
    screen16: new URL("./morsety-business/branches/16.png", import.meta.url)
      .href,
    screen17: new URL("./morsety-business/branches/17.png", import.meta.url)
      .href,
    screen18: new URL("./morsety-business/branches/18.png", import.meta.url)
      .href,
    screen19: new URL("./morsety-business/branches/19.png", import.meta.url)
      .href,
    screen20: new URL("./morsety-business/branches/20.png", import.meta.url)
      .href,
    screen21: new URL("./morsety-business/branches/21.png", import.meta.url)
      .href,
    screen22: new URL("./morsety-business/branches/22.png", import.meta.url)
      .href,
  },
  account: {
    screen1: new URL("./morsety-business/account/1.png", import.meta.url).href,
    screen2: new URL("./morsety-business/account/2.png", import.meta.url).href,
    screen3: new URL("./morsety-business/account/3.png", import.meta.url).href,
    screen4: new URL("./morsety-business/account/4.png", import.meta.url).href,
    screen5: new URL("./morsety-business/account/5.png", import.meta.url).href,
    screen6: new URL("./morsety-business/account/6.png", import.meta.url).href,
    screen7: new URL("./morsety-business/account/7.png", import.meta.url).href,
  },
  bookings: {
    screen1: new URL("./morsety-business/bookings/1.png", import.meta.url).href,
    screen2: new URL("./morsety-business/bookings/2.png", import.meta.url).href,
    screen3: new URL("./morsety-business/bookings/3.png", import.meta.url).href,
    screen4: new URL("./morsety-business/bookings/4.png", import.meta.url).href,
    screen5: new URL("./morsety-business/bookings/5.png", import.meta.url).href,
    screen6: new URL("./morsety-business/bookings/6.png", import.meta.url).href,
    screen7: new URL("./morsety-business/bookings/7.png", import.meta.url).href,
    screen8: new URL("./morsety-business/bookings/8.png", import.meta.url).href,
    screen9: new URL("./morsety-business/bookings/9.png", import.meta.url).href,
    screen10: new URL("./morsety-business/bookings/10.png", import.meta.url)
      .href,
  },
};
